# Generated by Django 3.2 on 2021-08-15 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artile',
            new_name='Article',
        ),
    ]
