# Generated by Django 3.2 on 2021-08-28 13:46

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(max_length=20, validators=[recipes.validators.validate_units]),
        ),
    ]
