# Generated by Django 3.2 on 2021-09-12 11:46

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_ingredient_quantity_as_float'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeimage',
            name='image',
            field=models.ImageField(default=None, upload_to=recipes.models.recipe_image_upload_handler),
            preserve_default=False,
        ),
    ]
